//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAlbumWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int Id { get; set; }
        public string Artistname { get; set; }
        public string Songs { get; set; }
        public string ArtistPic { get; set; }
    }
}
