//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAlbumWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicAlbum
    {
        public int Id { get; set; }
        public string Musicname { get; set; }
        public string Artist { get; set; }
        public string Musiclink { get; set; }
        public string Album { get; set; }
        public string Musicpic { get; set; }
        public Nullable<int> Hit { get; set; }
        public string Type { get; set; }
    }
}
